### ISSUE TITLE
🐛 No parameters matcher can not call from `expect.each().not`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-expect-each#24]
## Overview

* There is a bug in below code.

```
            // @ts-expect-error
            expect.each([
              receivedEntity,
              receivedEntity.CustomerDetail,
            ])
              .not
              .toBeNull()
```

```
    TypeError: Cannot read property 'map' of undefined

      64 |             ])
      65 |               .not
    > 66 |               .toBeNull()
         |                ^
      67 |           })
      68 |         })
      69 |       })

      at createExpectCaller (node_modules/@openreachtech/jest-expect-each/lib/setup.js:66:51)
      at Proxy.<anonymous> (node_modules/@openreachtech/jest-expect-each/lib/setup.js:31:9)
      at toBeNull (tests/__tests__/sequelize/scopes/Customer/J-CampanyDetail-J-CustomerDetail.js:66:16)
```

## Memo

* `toBeNull()` has no arguments, this is reason of this bug.

* Maybe, it will work.

```
            // @ts-expect-error
            expect.each([
              receivedEntity,
              receivedEntity.CustomerDetail,
            ])
              .not
              .toBe([
                null,
                null,
              ])
```

## Tasks

- [x] Add test to reproduce the bug.
- [x] ~Survey the bug.~
- [x] ~Restore the bug.~

**Comment by StewEucen** [comment]
Since adding new feature `.matcher.each()`, the bug has fixed automatically.
