### ISSUE TITLE
💪 When the number of actual and expected arrays are different

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-expect-each#25]
## Overview

* Decide the issue when the number of actual and expected arrays are different.

## Tasks

- [x] Decide spec on this issue.
  - [x] ~Finish, if not require to change the code.~
- [x] Throw error if different between actual and expected.

**Comment by StewEucen** [comment]
## Decided spec

* Require this function.

* There is a problem.

```
const expected = [1, 3, 5]

const received = targetClass.methdo()

// When received is empty array, can not be found the error by this `expect.each()`.
expect.each(received)
  .toBe(expected)
```

* Now, need it as follows:

```
const expected = [1, 3, 5]

const received = targetClass.methdo()

expect(received).toHaveLength(expected.length)
expect.each(received)
  .toBe(expected)
```
