### ISSUE TITLE
🚀 Publish as `0.1.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-expect-each#31]
## Overview

* Publish version as `0.1.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #32
- [x] Publish.
- [x] Merge to `main` as `0.1.0`.

## Procedure to Publish

0. Check Commit Hash to Publish

    - [x] git log --graph --oneline --decorate --all
    - [x] taget commit as: `b93b1c7` 

1. Comfirm Work to Publish

    - [x] To export new features correctly.
    - [x] Package version
        - [x] package.json
        - [x] package-lock.json
 
2. npm login to GitHub Packages

    - [x] get login password from your GitHub settings
Go to → https://github.com/settings/tokens
    - [x] copy your `personal access token` created
    - [x] run in terminal
        ```
        % npm login --registry=https://npm.pkg.github.com/

        Username: your-github-account-in-lower-case-only
        Password:
        Email: your.mail.account@gmail.com
        Logged in as [your-name] on https://npm.pkg.github.com/.
        ```

4. Publish

    - [x] `npm publish --dry-run`

        ```
        % npm publish --dry-run
        npm notice 
        npm notice 📦  @openreachtech/jest-expect-each@0.1.0
        npm notice === Tarball Contents === 
        npm notice 1.1kB LICENSE.md  
        npm notice 995B  README.md   
        npm notice 3.3kB lib/setup.js
        npm notice 912B  package.json
        npm notice === Tarball Details === 
        npm notice name:          @openreachtech/jest-expect-each          
        npm notice version:       0.1.0                                    
        npm notice filename:      @openreachtech/jest-expect-each-0.1.0.tgz
        npm notice package size:  2.4 kB                                   
        npm notice unpacked size: 6.3 kB                                   
        npm notice shasum:        097e6e3c2b5256eba1513798cb40e6ddbb82490f 
        npm notice integrity:     sha512-NI4G5FItIq3M4[...]M/NrFTSAWApkA== 
        npm notice total files:   4                                        
        npm notice 
        + @openreachtech/jest-expect-each@0.1.0
        ```

    - [x] Check log of `--dry-run` by other member before actual publishing.
    - [x] `npm publish`

**Comment by JYama321** [comment]
I got the following result by `npm publish --dry-run` at commit hash `b93b1c7476fab50888a097df3358d96df6ef25e8 `.

```
npm notice
npm notice 📦  @openreachtech/jest-expect-each@0.1.0
npm notice === Tarball Contents ===
npm notice 1.1kB LICENSE.md
npm notice 995B  README.md
npm notice 3.3kB lib/setup.js
npm notice 912B  package.json
npm notice === Tarball Details ===
npm notice name:          @openreachtech/jest-expect-each
npm notice version:       0.1.0
npm notice filename:      @openreachtech/jest-expect-each-0.1.0.tgz
npm notice package size:  2.4 kB
npm notice unpacked size: 6.3 kB
npm notice shasum:        097e6e3c2b5256eba1513798cb40e6ddbb82490f
npm notice integrity:     sha512-NI4G5FItIq3M4[...]M/NrFTSAWApkA==
npm notice total files:   4
npm notice
+ @openreachtech/jest-expect-each@0.1.0
```
