### ISSUE TITLE
⚙️ Add `jsconfig.json` to purge `// @ts-check`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-expect-each#40]
## Overview

* Add `jsconfig.json` to purge `// @ts-check`.

## Tasks

- [x] Add `jsconfig.json`.
- [x] Remove `// @ts-check` from all files.
- [x] Update `README.md`.
