### ISSUE TITLE
🧪 add test cases

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/jest-expect-each#8]
## Overview

* Add test case for all cases.

* See https://jestjs.io/ja/docs/expect

## Tasks

 - [x] Grouping below tasks by priority
  
### Single

- [x] `.toBe(value)`
- [ ] `.toHaveBeenCalledTimes(number)` (= `.toBeCalledTimes(number)`)
- [ ] `.toHaveReturnedTimes(number)` (= `.toReturnTimes(number)`)
- [ ] `.toHaveReturnedWith(value)` (= `.toHaveReturnedWith(value)`)
- [ ] `.toHaveLastReturnedWith(value)`
- [ ] `.toHaveLength(number)`
- [ ] `.toBeGreaterThan(number | bigint)`
- [ ] `.toBeGreaterThanOrEqual(number | bigint)`
- [ ] `.toBeLessThan(number | bigint)`
- [ ] `.toBeLessThanOrEqual(number | bigint)`
- [ ] `.toBeInstanceOf(Class)`
- [ ] `.toContain(item)`
- [ ] `.toContainEqual(item)`
- [ ] `.toEqual(value)`
- [ ] `.toMatch(regexp | string)`
- [ ] `.toMatchObject(object)`
- [ ] `.toStrictEqual(value)`
- [ ] `.toThrow(error?)` (= `.toThrowError(error?)`)
- [ ] `.toThrowErrorMatchingSnapshot(hint?)`
- [ ] `.toThrowErrorMatchingInlineSnapshot(inlineSnapshot)`

### Zero

- [ ] `.toHaveBeenCalled()` (= `.toBeCalled()`)
- [ ] `.toHaveReturned()` (= `.toReturn()`)
- [ ] `.toBeDefined()`
- [ ] `.toBeFalsy()`
- [x] `.toBeNull()`
- [ ] `.toBeTruthy()`
- [ ] `.toBeUndefined()`
- [ ] `.toBeNaN()`

### Multiple

- [ ] `.toHaveBeenCalledWith(arg1, arg2, ...)` (= `.toBeCalledWith(arg1, arg2, ...)`)
- [ ] `.toHaveBeenLastCalledWith(arg1, arg2, ...)` (= `.lastCalledWith(arg1, arg2, ...)`)
- [ ] `.toHaveBeenNthCalledWith(nthCall, arg1, arg2, ....)` (= `.nthCalledWith(nthCall, arg1, arg2, ....)`)
- [ ] `.toHaveLastReturnedWith(nthCall, value)` (= `.lastReturnedWith(nthCall, value)`)
- [ ] `.toHaveNthReturnedWith(nthCall, value)` (= `.nthReturnedWith(nthCall, value)`)
- [ ] `.toHaveProperty(keyPath, value?)`
- [x] `.toBeCloseTo(number, numDigits?)`
- [ ] `.toMatchSnapshot(propertyMatchers?, hint?)`
- [ ] `.toMatchInlineSnapshot(propertyMatchers?, inlineSnapshot)`
